//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountdownApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CountdownApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert.
        /// </summary>
        public static string AlarmText {
            get {
                return ResourceManager.GetString("AlarmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Light.
        /// </summary>
        public static string AlwaysLightText {
            get {
                return ResourceManager.GetString("AlwaysLightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItem.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an ad-free version.
        /// </summary>
        public static string BuyFullVersion {
            get {
                return ResourceManager.GetString("BuyFullVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not ask me again.
        /// </summary>
        public static string CheckBoxContent {
            get {
                return ResourceManager.GetString("CheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop what you&apos;re doing..
        /// </summary>
        public static string CustomerMessageBoxCation {
            get {
                return ResourceManager.GetString("CustomerMessageBoxCation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szooze for:.
        /// </summary>
        public static string CustomerMessageBoxHeader {
            get {
                return ResourceManager.GetString("CustomerMessageBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szooze.
        /// </summary>
        public static string CustomerMessageBoxLeftButton {
            get {
                return ResourceManager.GetString("CustomerMessageBoxLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dismiss.
        /// </summary>
        public static string CustomerMessageBoxRightButton {
            get {
                return ResourceManager.GetString("CustomerMessageBoxRightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default time.
        /// </summary>
        public static string DefaultTimeText {
            get {
                return ResourceManager.GetString("DefaultTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current version is a trial version, timing features are disabled. Do you want to upgrade to full version?.
        /// </summary>
        public static string DownloadFullVersionMsg {
            get {
                return ResourceManager.GetString("DownloadFullVersionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the Full Version.
        /// </summary>
        public static string DownloadFullVersionTitle {
            get {
                return ResourceManager.GetString("DownloadFullVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ErrorTitleText {
            get {
                return ResourceManager.GetString("ErrorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Confirmation.
        /// </summary>
        public static string ExitConfirmCheckBoxText {
            get {
                return ResourceManager.GetString("ExitConfirmCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ExitConfirmMsg {
            get {
                return ResourceManager.GetString("ExitConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes.
        /// </summary>
        public static string FiveMinutes {
            get {
                return ResourceManager.GetString("FiveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 hours.
        /// </summary>
        public static string FourHours {
            get {
                return ResourceManager.GetString("FourHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Spread the Word.
        /// </summary>
        public static string MsgBoxCaption {
            get {
                return ResourceManager.GetString("MsgBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe Later.
        /// </summary>
        public static string MsgBoxLeftBtn {
            get {
                return ResourceManager.GetString("MsgBoxLeftBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like this app, please rate it in the App Store. Thanks!.
        /// </summary>
        public static string MsgBoxMsg {
            get {
                return ResourceManager.GetString("MsgBoxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate It Now.
        /// </summary>
        public static string MsgBoxRightBtn {
            get {
                return ResourceManager.GetString("MsgBoxRightBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        public static string OneMinute {
            get {
                return ResourceManager.GetString("OneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string OrText {
            get {
                return ResourceManager.GetString("OrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate.
        /// </summary>
        public static string RateUs {
            get {
                return ResourceManager.GetString("RateUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string RepeatText {
            get {
                return ResourceManager.GetString("RepeatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-GB.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Property.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the last selected time.
        /// </summary>
        public static string SaveTheLastTimeText {
            get {
                return ResourceManager.GetString("SaveTheLastTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Sound.
        /// </summary>
        public static string SecondSoundText {
            get {
                return ResourceManager.GetString("SecondSoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string SelectCountdownMsg {
            get {
                return ResourceManager.GetString("SelectCountdownMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First of all thank you for using this application, if you have good ideas or suggestions, please do not begrudge us, may be added to the next version of your good ideas!.
        /// </summary>
        public static string SendEmailContentText {
            get {
                return ResourceManager.GetString("SendEmailContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a email to the developers?.
        /// </summary>
        public static string SendEmailTitleText {
            get {
                return ResourceManager.GetString("SendEmailTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string SoundNoneText {
            get {
                return ResourceManager.GetString("SoundNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string SoundText {
            get {
                return ResourceManager.GetString("SoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vibrate.
        /// </summary>
        public static string SoundVibrateText {
            get {
                return ResourceManager.GetString("SoundVibrateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartMenu {
            get {
                return ResourceManager.GetString("StartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopMenu {
            get {
                return ResourceManager.GetString("StopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes.
        /// </summary>
        public static string TenMinutes {
            get {
                return ResourceManager.GetString("TenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string UnChecked {
            get {
                return ResourceManager.GetString("UnChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timing.
        /// </summary>
        public static string UnderwayTitle {
            get {
                return ResourceManager.GetString("UnderwayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time must be greater than 0!.
        /// </summary>
        public static string ValidateTimeMsg {
            get {
                return ResourceManager.GetString("ValidateTimeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
